# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
- stage: Build
  jobs:
  - job: FirstJob
    steps:
    - bash: echo $(PipelineLevelVariable)
    - bash: echo $(PipelineLevelVariable)
    - bash: echo $(Build.BuildNumber)
    - bash: echo $(Build.BuildId)
    - bash: echo $(Build.SourceBranchName)
    - bash: echo $(Build.SourcesDirectory)
    - bash: echo $(System.DefaultWorkingDirectory)
    - bash: ls -R $(System.DefaultWorkingDirectory)
    - bash: echo $(Build.ArtifactStagingDirectory)
#   - job: SecondJob
#     steps:
#     - bash: echo Build SecondJob
# - stage: DevDeploy
#   dependsOn: Build
#   jobs:
#   - job: BuildJob
#     steps:
#     - bash: echo Build Dev
# - stage: QADeploy
#   dependsOn: Build
#   jobs:
#   - job: QAJob
#     steps:
#     - bash: echo QA Job
# - stage: ProDeploy
#   dependsOn: 
#   - DevDeploy
#   - QADeploy
#   jobs:
#   - job: ProJob
#     steps:
#     - bash: echo Pro Job
 
